name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Check out my other private repo
      uses: actions/checkout@master
      with:
        repository: deepmind/alphafold
    
#git clone https://github.com/deepmind/alphafold.git
#cd alphafold
#sudo docker build -f docker/Dockerfile -t alphafold .
#sudo docker run -d -p 5000:5000 --restart=always --name registry registry:2
#sudo docker image tag alphafold:latest localhost:5000/alphafold:latest
##sudo docker push localhost:5000/alphafold:latest
#sudo SINGULARITY_NOHTTPS=true singularity build alphafold.sif docker://localhost:5000/alphafold:latest
