name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check out my other private repo
      uses: actions/checkout@master
      with:
        repository: deepmind/alphafold
    - name: disk size
      run: lsblk
    - name: Current usage
      run: df -h
