name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Check out my other private repo
      uses: actions/checkout@master
      with:
        repository: deepmind/alphafold
    - name: Build docker image locally
      run: sudo docker build -f docker/Dockerfile -t alphafold .
    - name: Start docker image
      run: sudo docker run -d -p 5000:5000 --restart=always --name registry registry:2
    - name: Tag image
      run: sudo docker image tag alphafold:latest localhost:5000/alphafold:latest
    - name: Push image to local docker library
      run: sudo push localhost:5000/alphafold:latest
    - name: Install singularity
      run: |
        sudo add-apt-repository -y ppa:apptainer/ppa
        sudo apt update
        sudo apt install -y apptainer
    - name: Build Singularity image
      run: sudo SINGULARITY_NOHTTPS=true singularity build alphafold.sif docker://localhost:5000/alphafold:latest
